name = "MoneySim"
uuid = "2c321c3e-df22-4fe8-8a60-238a5a5a30c9"
authors = ["Stef Kuypers <stef@happonomy.org>, Thomas Goorden <thomas.goorden@gmail.com>"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
EconoSim = "cc8cb6e0-4c11-4d04-b964-59e7aacda730"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1.5"
